name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: check make version
      run: make --version
      
    - name: install dependencies
      run: make install
      
    - name: Run tests
      run: make test
